#!/usr/bin/env bash
# deploy.sh — GENERIC STUB generated by leadv2-init (no matching stack example found)
# TODO: Replace the body below with your actual deploy commands.
#
# Common patterns:
#   Vercel:     cd web && vercel --prod --yes
#   VPS:        ssh user@host "cd /app && git pull && systemctl restart myapp"
#   Docker:     docker build -t app . && docker push registry/app && kubectl rollout restart deploy/app
#   Static:     aws s3 sync dist/ s3://bucket --delete
#
# Required env: LEAD_V2_TASK_ID (injected by lead automatically)
# Write the final deploy URL to /tmp/leadv2-last-deploy-url so verify.sh can use it.
set -euo pipefail

log() { printf -- '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*" >&2; }

: "${LEAD_V2_TASK_ID:?LEAD_V2_TASK_ID env required}"

log "deploy.sh: task=$LEAD_V2_TASK_ID"
log "ERROR: deploy.sh is a stub — replace with real deploy commands before running leadv2 tasks"
log "See: ~/.claude/plugins/leadv2/examples/overrides/ for working examples"

# Intentional non-zero exit: stub must not silently pass.
# Once you have filled in real commands, remove this exit line.
exit 1
