#!/usr/bin/env bash
# outcome-watch.sh — GENERIC STUB generated by leadv2-init (no matching stack example found)
# TODO: Replace with a real post-deploy stability watch.
#
# Common patterns:
#   HTTP polling:   while true; do curl -fsS $URL/health || echo "DEGRADED"; sleep 15; done
#   Log tail:       ssh user@host "tail -F /var/log/app/cycle.log"
#   k8s:            kubectl rollout status deploy/app --timeout=300s
#
# Exit 0 = stable, non-zero = unstable
set -euo pipefail

: "${LEAD_V2_TASK_ID:?LEAD_V2_TASK_ID env required}"

echo "[outcome-watch] WARNING: outcome-watch.sh is a stub — no watch configured"
echo "[outcome-watch] Skipping watch (exit 0). Fill in a real watch to catch post-deploy regressions."
echo "[outcome-watch] See: ~/.claude/plugins/leadv2/examples/overrides/ for working examples"

# Exit 0 (warning-only): unlike verify.sh, a missing outcome-watch is non-fatal.
# The deploy + verify pair is the primary gate; outcome-watch is continuous health only.
exit 0
