#!/usr/bin/env bash
# verify.sh — GENERIC STUB generated by leadv2-init (no matching stack example found)
# TODO: Replace the body below with a real health check.
#
# Common patterns:
#   HTTP endpoint:  curl -fsS https://yourapp.example.com/api/health
#   VPS service:    ssh user@host "systemctl is-active myapp.service"
#   Docker:         docker run --rm curlimages/curl curl -fsS http://app/health
#
# Exit 0 = healthy, non-zero = unhealthy (leadv2 will mark task as failed)
set -euo pipefail

: "${LEAD_V2_TASK_ID:?LEAD_V2_TASK_ID env required}"

echo "[verify] ERROR: verify.sh is a stub — no health check configured"
echo "[verify] Fill in a real check or copy from: ~/.claude/plugins/leadv2/examples/overrides/"
echo "[verify] Until this is filled in, verification will always fail (intentional — silent pass = false confidence)"

# Intentional non-zero exit: stubs must be LOUD, not silent.
exit 1
